title: Victor Morales
email: chipahuac@hotmail.com
description: >
    This blog is a complementary of the articles published in
    http://electrocucaracha.com and pretends to collect articles
    written in english.
baseurl: "/"
url: "http://electrocucaracha.github.io"
twitter_username: electrocucarach
github_username:  electrocucaracha
rss: rss
flickr_username: electrocucaracha
linkedin_username: electrocucaracha

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
